const SET_ONBOARDING = 'app/SET_ONBOARDING';
// const GET_APPINIT = 'app/GET_APPINIT';
// const GET_APPINIT_SUCCESS = 'app/GET_APPINIT_SUCCESS';
// const GET_APPINIT_FAILURE = 'app/GET_APPINIT_FAILURE';

export default {
  SET_ONBOARDING,
  // GET_APPINIT,
  // GET_APPINIT_SUCCESS,
  // GET_APPINIT_FAILURE,
};
